### ISSUE TITLE
Crashes on large files

### ISSUE THREAD

**Issue by anson-vandoren** [minOnlinRepo/log-collector-project#2]
I tested this with a large syslog file (~2GB) and requested the last 10mil lines. The backend service crashed after several seconds with:

```
--- /getLog request------/home/anson/Downloads/syslog.log,  10000000, 
/home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/express/lib/response.js:1150
    : JSON.stringify(value);
           ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/express/lib/response.js:1150:12)
    at ServerResponse.json (/home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/express/lib/response.js:271:14)
    at ServerResponse.send (/home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/express/lib/response.js:162:21)
    at Stream.handleEndOfFileData (/home/anson/src/takehome/min/log-collector-project/log-collect-service/logCollect.js:50:37)
    at Stream.emit (events.js:412:35)
    at Stream.<anonymous> (/home/anson/src/takehome/min/log-collector-project/log-collect-service/logCollect.js:34:32)
    at Stream.emit (events.js:400:28)
    at data (/home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/fs-reverse/index.js:59:16)
    at /home/anson/src/takehome/min/log-collector-project/log-collect-service/node_modules/fs-reverse/index.js:45:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! log-collect-service@1.0.0 start: `node logCollect.js `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the log-collect-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anson/.npm/_logs/2022-06-13T16_10_49_187Z-debug.log

```

It would be great if the service can handle arbitrarily large files.

**Comment by anson-vandoren** [comment]
Does not crash any more, but it seems that not all lines are returned/displayed still. Closing this issue since this falls more under #4
